from collections import Counter

data_dict = {}
data = ">Rosalind_6404 \
CCTGCGGAAGATCGGCACTAGAATAGCCAGAACCGTTTCTCTGAGGCTTCCGGCCTTCCC \
TCCCACTAATAATTCTGAGG\
>Rosalind_5959\
CCATCGGTAGCGCATCCTTAGTCCAATTAAGTCCCTATCCAGGCGCTCCGCCGAAGGTCT\
ATATCCATTTGTCAGCAGACACGC\
>Rosalind_0808\
CCACCCTCGTGGTATGGCTAGGCATTCAGGAACCGGAGAACGCTTCAGACCAGCCCGGAC\
TGGGAACCTGCGGGCAGTAGGTGGAAT"
datas = data.split(">")[1:]
for data in datas:
    name = data[:13]
    data = Counter(data[14:].replace(" ", ""))
    data_dict[name] = data["C"] + data["G"]

